before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos:  windows
        goarch: arm64
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - 'ghcr.io/denizgursoy/clerk:{{ .Tag }}'
      - 'ghcr.io/denizgursoy/clerk:latest'
    dockerfile: build/package/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/denizgursoy/clerk/main/README.md"
      - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Deniz Gursoy\",\"email\":\"denizgursoy.443@gmail.com\"}]"
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.description=Clerk"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
      - "--build-arg=ALPINE=alpine:3.16.2"
